### ISSUE TITLE
Solana Tx fails more than half of the time..

### ISSUE THREAD

**Issue by rjoshig** [wormhole-foundation/connect-sdk#192]
I have been playing around with tokenBridge and have come across few blockers as i navigate my way through.
You guys have been helpful in debugging or fixing some of the things i do.

I am mainly using the tokenBridge program that @barnji created.. it helps to understand how the connect sdk is structured.
I am mainly testing native transfers from Solana to Moonbeam or Fantom(EVM) and EVM chain to Solana.

I realized that for the most part  50% of time, tx will fail on Solana chain.. either during initiating or completing transfers.
I feel like there needs to be an improvement made in the the signSendWait. From what I figured, it has something to do with transaction retries.

Below is the error i normally see.. It works 50% of the time..

```

Completing Transfer
Signing: Core.VerifySignature for 5cNqDp7xxxxr6iyuG
Signing: Core.VerifySignature for 5cNqxxxx6iyuG
Signing: Core.PostVAA for 5cNqxxxyxG
/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/node_modules/@solana/web3.js/src/connection.ts:5054
      throw new SendTransactionError(
            ^
SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
    at Connection.sendEncodedTransaction (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/node_modules/@solana/web3.js/src/connection.ts:5054:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.sendRawTransaction (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/node_modules/@solana/web3.js/src/connection.ts:5013:20)
    at async Promise.all (index 0)
    at async Function.sendWait (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/src/platform.ts:168:22)
    at async signSendWait (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk/src/common.ts:44:25)
    at async TokenTransfer.completeTransfer (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk/src/protocols/tokenTransfer.ts:250:25)
    at async tokenTransfer (/home/rjoshig/private/sandbox/solana/wormhole/src/wormhole_test.ts:451:23)
    at async Bridge (/home/rjoshig/private/sandbox/solana/wormhole/src/wormhole_test.ts:364:9)
    at async main (/home/rjoshig/private/sandbox/solana/wormhole/src/wormhole_test.ts:200:13) {
  logs: [
    'Program worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth invoke [1]',
    'Program log: Error: IoError(Custom { kind: InvalidInput, error: "Unexpected length of input" })',
    'Program worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth consumed 19627 of 200000 compute units',
    'Program worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth failed: custom program error: 0x0'
  ]

```

**Comment by rjoshig** [comment]
Another issue which is pretty common.. This I think is again related to the same issue as above..

```

------------------------- ----------------- -----------------------------
Starting transfer
Signing: TokenBridge.TransferNative for xxFxxxASRxC8xx
/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/node_modules/@solana/web3.js/src/connection.ts:5054
      throw new SendTransactionError(
            ^
SendTransactionError: failed to send transaction: Transaction simulation failed: Blockhash not found
    at Connection.sendEncodedTransaction (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/node_modules/@solana/web3.js/src/connection.ts:5054:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.sendRawTransaction (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/node_modules/@solana/web3.js/src/connection.ts:5013:20)
    at async Promise.all (index 0)
    at async Function.sendWait (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/src/platform.ts:168:22)
    at async signSendWait (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk/src/common.ts:44:25)
    at async TokenTransfer.initiateTransfer (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk/src/protocols/tokenTransfer.ts:186:18)
    at async tokenTransfer (/home/rjoshig/private/sandbox/solana/wormhole/src/wormhole_test.ts:452:22)
    at async Bridge (/home/rjoshig/private/sandbox/solana/wormhole/src/wormhole_test.ts:388:9)
    at async main (/home/rjoshig/private/sandbox/solana/wormhole/src/wormhole_test.ts:212:17) {
  logs: []
}


```

**Comment by rjoshig** [comment]
This is an example of completing transfers between Fantom and Solana.. Hope all these provides more context on the issue:


```

Completing Transfer
Signing: Redeem.CreateATA for xxxC83hy
Signing: Core.VerifySignature for xxti9CCKTtxxhy
Signing: Core.VerifySignature for xx83hy
Signing: Core.PostVAA for xxx3hy
/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/node_modules/@solana/web3.js/src/connection.ts:5054
      throw new SendTransactionError(
            ^
SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
    at Connection.sendEncodedTransaction (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/node_modules/@solana/web3.js/src/connection.ts:5054:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.sendRawTransaction (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/node_modules/@solana/web3.js/src/connection.ts:5013:20)
    at async Promise.all (index 0)
    at async Function.sendWait (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/src/platform.ts:168:22)
    at async signSendWait (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk/src/common.ts:44:25)
    at async TokenTransfer.completeTransfer (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk/src/protocols/tokenTransfer.ts:250:25)
    at async tokenTransfer (/home/rjoshig/private/sandbox/solana/wormhole/src/wormhole_test.ts:475:23)
    at async Bridge (/home/rjoshig/private/sandbox/solana/wormhole/src/wormhole_test.ts:388:9)
    at async main (/home/rjoshig/private/sandbox/solana/wormhole/src/wormhole_test.ts:212:17) {
  logs: [
    'Program worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth invoke [1]',
    'Program log: Error: IoError(Custom { kind: InvalidInput, error: "Unexpected length of input" })',
    'Program worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth consumed 19627 of 200000 compute units',
    'Program worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth failed: custom program error: 0x0'
  ]
}

```

**Comment by rjoshig** [comment]
Another one .. while signing.. all related to sendTransaction.......

```


Starting transfer
Signing: TokenBridge.TransferNative for xxxJiGjxxMxxx
/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/node_modules/@solana/web3.js/src/connection.ts:3456
          throw new TransactionExpiredBlockheightExceededError(rawSignature);
                ^
TransactionExpiredBlockheightExceededError: Signature TiupatTWKZjEoBNexK5PYT9Bq66skEfeEJYeNNvRrMBmx2wGbgEfo1tCfSeoXj4vSZ7FVGajeKWwG8BMhW4i6W4 has expired: block height exceeded.
    at Connection.confirmTransaction (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/node_modules/@solana/web3.js/src/connection.ts:3456:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async Function.sendWait (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk-solana/src/platform.ts:176:5)
    at async signSendWait (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk/src/common.ts:44:25)
    at async TokenTransfer.initiateTransfer (/home/rjoshig/private/sandbox/solana/wormhole/node_modules/@wormhole-foundation/connect-sdk/src/protocols/tokenTransfer.ts:186:18)
    at async tokenTransfer (/home/rjoshig/private/sandbox/solana/wormhole/src/wormhole_test.ts:453:22)
    at async Bridge (/home/rjoshig/private/sandbox/solana/wormhole/src/wormhole_test.ts:389:9)
    at async main (/home/rjoshig/private/sandbox/solana/wormhole/src/wormhole_test.ts:212:17) {
  signature: 'TiupatTWKZjEoBNexK5PYT9Bq6xxx2wGbgxxtCfSeoxxGajeKWwG8BMxx6Wx'
```

**Comment by barnjamin** [comment]
Filed https://github.com/wormhole-foundation/connect-sdk/pull/195 to address this
