### ISSUE TITLE
CCTP: No protocol registered for Solana:AutomaticCircleBridge

### ISSUE THREAD

**Issue by ConjunctiveNormalForm** [wormhole-foundation/connect-sdk#240]
I'm testing out a small script that is mostly based on the cctp example:
```
  const wh = new Wormhole("Mainnet", [EvmPlatform, SolanaPlatform]);

    source = await getStuff(wh.getChain("Base"));
    destination = await getStuff(wh.getChain("Solana"));

  await cctpTransfer(wh, source, destination, {
    amount,
    automatic: true,
    nativeGas: undefined,
  });
}
```

Using version `0.3.0-beta.16` of all the dependencies:
```
    "@wormhole-foundation/connect-sdk": "0.3.0-beta.16",
    "@wormhole-foundation/connect-sdk-evm": "0.3.0-beta.16",
    "@wormhole-foundation/connect-sdk-evm-cctp": "0.3.0-beta.16",
    "@wormhole-foundation/connect-sdk-evm-core": "^0.2.6",
    "@wormhole-foundation/connect-sdk-solana": "0.3.0-beta.16",
    "@wormhole-foundation/connect-sdk-solana-cctp": "0.3.0-beta.16"
```

Stack trace
```
Error: No protocol registered for Solana:AutomaticCircleBridge
    at getProtocolInitializer (/cctp/node_modules/@wormhole-foundation/sdk-definitions/src/protocol.ts:78:20)
    at create (/cctp/node_modules/@wormhole-foundation/sdk-definitions/src/protocol.ts:89:16)
    at SolanaPlatform.getProtocol (/cctp/node_modules/@wormhole-foundation/sdk-definitions/src/platform.ts:106:18)
    at SolanaChain.getAutomaticCircleBridge (/cctp/node_modules/@wormhole-foundation/sdk-definitions/src/chain.ts:143:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Wormhole.circleTransfer (/cctp/node_modules/@wormhole-foundation/connect-sdk/src/wormhole.ts:99:19)
    at cctpTransfer (/cctp/src/index.ts:35:16)
```

**Comment by barnjamin** [comment]
No AutomaticCircleBridge exists for Solana. 

In fact the native usdc transfers are only available on devnet for Solana at the moment.

If you do get this sort of error for _other_ protocols, be sure to register the proto as in this [example](https://github.com/wormhole-foundation/connect-sdk/blob/main/examples/src/tokenBridge.ts#L18-L21)

**Comment by ConjunctiveNormalForm** [comment]
> In fact the native usdc transfers are only available on devnet for Solana at the moment.

Ah okay, that explains the various errors I've been getting. Thanks!
