### ISSUE TITLE
TypeError When Using @wormhole-foundation/connect-sdk-evm with Solana and EVM Signers

### ISSUE THREAD

**Issue by infra403** [wormhole-foundation/connect-sdk#320]
# Description:
I encountered a TypeError: Class extends value undefined is not a constructor or null when attempting to use the Wormhole Foundation's Connect SDK for Solana and EVM. This error occurred while running code intended to abstract the process of getting signers for both Solana and EVM platforms. Below is the error message received:
```TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/node_modules/@wormhole-foundation/connect-sdk-evm/src/signer.ts:35:11)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Object.require.extensions.<computed> [as .js] (/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/src/wormhole/transfer.ts:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
```

# Expected Behavior:
The expected behavior is for the code to correctly return a signer object for both Solana and EVM platforms without throwing any errors.

# Environment:
Node.js version: [20.4.0]
@wormhole-foundation/connect-sdk-solana version: [^0.3.3]
@wormhole-foundation/connect-sdk-evm version: [^0.3.3]

# Code Snippet to Reproduce:
```
import {getSolanaSignAndSendSigner} from "@wormhole-foundation/connect-sdk-solana/dist/cjs/signer";
import {getEvmSignerForKey} from "@wormhole-foundation/connect-sdk-evm/dist/cjs/signer";
export async function getStuff<
  N extends Network,
  P extends Platform,
  C extends PlatformToChains<P>,
>(chain: ChainContext<N, P, C>, privateKey: string): Promise<TransferStuff<N, P, C>> {
  let signer: Signer;
  const platform = chain.platform.utils()._platform;
  switch (platform) {
    case "Solana":
      signer = await getSolanaSignAndSendSigner(await chain.getRpc(), privateKey, {
        computeLimit: 500_000n,
      });
      break;
    case "Evm":
      signer = await getEvmSignerForKey(await chain.getRpc(), privateKey);
      break;
    default:
      throw new Error("Unrecognized platform: " + platform);
  }

  return {
    chain,
    signer: signer as Signer<N, C>,
    address: Wormhole.chainAddress(chain.chain, signer.address()),
  };
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "declaration": true,
    "importHelpers": true,
    "module": "commonjs",
    "outDir": "dist",
    "rootDir": "src",
    "strict": false,
    "target": "es2020",
    "strictNullChecks": false,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitAny": false,
    "strict": false,
    "skipLibCheck": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules/*"
  ]
}

```

**Comment by barnjamin** [comment]
hello, the trace doesn't contain anything that makes it very obvious what the issue is but I suspect the issue is in these lines:

```ts
import {getSolanaSignAndSendSigner} from "@wormhole-foundation/connect-sdk-solana/dist/cjs/signer";
import {getEvmSignerForKey} from "@wormhole-foundation/connect-sdk-evm/dist/cjs/signer";
```

instead, for 0.3.x, try 
```ts
import {testing as solTesting} from "@wormhole-foundation/connect-sdk-solana";
import {testing as evmTesting} from "@wormhole-foundation/connect-sdk-evm";
```

and call the appropriate `testing.getXXXSigner` method.

The main branch of the sdk is @ 0.4.0-beta.x and the Signer has been moved to the root so the testing import should not be necessary
